version: '3'

services:
  mariadb_v1_1:
    image: 'bitnami/mariadb:10.6'
    container_name: mariadb_ed_v1_1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=blog
    networks:
      - laravel_network_v1_1
    volumes:
      - mariadb_data_v1_1:/bitnami/mariadb

  laravel_v1_1:
    image: 'bitnami/laravel:9'
    container_name: laravel_ed_v1_1
    ports:
      - '4115:8000'
    environment:
      - DB_HOST=mariadb_v1_1
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=blog
    networks:
      - laravel_network_v1_1
    volumes:
      - ./casi2:/app

  phpmyadmin_v1_1:
    image: 'phpmyadmin:5.2'
    container_name: phpmyadmin_ed_v1_1
    ports:
      - '4116:80'
    environment:
      PMA_HOST: mariadb
      PMA_USER: bn_myapp
      PMA_PASSWORD: ''
    depends_on:
      - mariadb_v1_1
    networks:
      - laravel_network_v1_1

networks:
  laravel_network_v1_1:
    driver: bridge

volumes:
  mariadb_data_v1_1:
    driver: local
